### ISSUE TITLE
Modman file not up to date

### ISSUE THREAD

**Issue by mvscheidt** [cobbyio/cobby-connector-magento#7]
The modman file references files / folders that no longer exist

https://github.com/cobbyio/cobby-connector-magento/blob/master/modman

When installing via composer this causes the following error to appear because `src/app/design` does no longer exist

```
[ErrorException]                                                                                                                      
Source /var/www/html/vendor/cobbyio/cobby-connector-magento/src/app/design/adminhtml/default/default/layout/cobby.xml does not exist
```

**Comment by wDackel** [comment]
Hey @mvscheidt.

thank you for your report! 
We fixed this issue in the new version [2.4.2](https://github.com/cobbyio/cobby-connector-magento/releases/tag/2.4.2). 🚀 
If you have any problems in this regard, please let us know. 

Best regards
